## [`sympy`](https://docs.sympy.org/latest/guides/index.html#)

In [3]:
import sympy as sp # SymPy is a Python library for symbolic mathematics. 
from sympy import *
from sympy import Matrix
import pandas as pd
import numpy as np


# init_printing(use_unicode=True) #This will make all further examples pretty print with unicode characters.

x, t, z, nu = symbols('x t z nu') #  define variables

In [4]:
A = Matrix([[5, -3, x], [1, 1, -2], [2, x + 2, -1]])
A

Matrix([
[5,    -3,  x],
[1,     1, -2],
[2, x + 2, -1]])

In [5]:
det = A.det()
# det  Calculates matrix determinant
det

x**2 + 10*x + 24

In [6]:
print(sp.solve(det))
print(sum(sp.solve(det)))

[-6, -4]
-10


symbolic power SymPy

In [7]:
sp.sqrt(8) # !!!

2*sqrt(2)

Take the derivative of $sin(x)e^x$

In [8]:
diff(sin(x)*exp(x), x)

exp(x)*sin(x) + exp(x)*cos(x)

Compute $\int_{}^{} e^x sin(x) + e^x cos(x) d(x)$

In [9]:
integrate(exp(x)*sin(x) + exp(x)*cos(x), x)

exp(x)*sin(x)

Compute $\int_{-\infty}^{\infty} sin(x^2) dx$

In [10]:
integrate(sin(x**2), (x, -oo, oo))

sqrt(2)*sqrt(pi)/2

Find $\lim_{x \to 0} \frac{sin(x)}{x}$

In [11]:
limit(sin(x)/x, x, 0)

1

Solve: $ x^2 - 2 = 0$

In [12]:
solve(x**2 - 2, x)

[-sqrt(2), sqrt(2)]

Solve the differential equation 
$y''  - y = e^t$

In [13]:
y = Function('y')
dsolve(Eq(y(t).diff(t, t) - y(t), exp(t)), y(t))
# The "dsolve" function is called with two arguments: the differential equation and 
# the dependent variable "y(t)". The "dsolve" function returns the general solution to the 
# differential equation, which can be displayed using the "print" function.

# The output of the code is the general solution to the differential equation, which is 
# expressed in terms of unknown functions and constants. To find the specific solution for 
# a particular set of initial conditions, we would need to substitute specific values for 
# these unknowns and constants.

Eq(y(t), C2*exp(-t) + (C1 + t/2)*exp(t))

Print  
$\int\limits_{0}^{\pi} \cos^{2}{\left(x \right)}\, dx$  
  using LATEX

In [14]:
sp.latex(Integral(cos(x)**2, (x, 0, pi)))

'\\int\\limits_{0}^{\\pi} \\cos^{2}{\\left(x \\right)}\\, dx'

`simplify` performs only in cases valid for all possible values

In [15]:
q = Symbol('q') # positive, negative and 0
simplify( sqrt( q ** 2) )

sqrt(q**2)

In [16]:
q = Symbol('q', positive = True) # positive, negative and 0
simplify( sqrt( q ** 2) )

q

Вычислить с помощью Python значение первой производной для функции $8x(x+3)^2$ в точке $x=1$


In [17]:
x = sp.Symbol('x')  # define x as analitycal parameter
8*x*(x+3)**2

8*x*(x + 3)**2

In [18]:
res = sp.diff(8*x*(x+3)**2, x) #  Differentiate f with respect to symbols.
res

8*x*(2*x + 6) + 8*(x + 3)**2

In [19]:
# значение первой производной в точке x=1
res.subs(x,1) #  change 'x' to 1

192

In [20]:
res.evalf(subs={'x':1})

192.000000000000

In [21]:
# 
diff(sin(x), x)

cos(x)

In [22]:
f = Function('f')
diff(f(x), x, 2)
#  Differentiate f with respect to symbols.
#  diff(f(x), x, x, x) and diff(f(x), x, 3) both return the third derivative of f(x).

Derivative(f(x), (x, 2))

In [23]:
y = Symbol('y')
a = Symbol('a')
diff(sin(x)*cos(y), x, 1, y, 1)
# The expression "diff(sin(x)*cos(y), x, 2, y, 2)" is a request to compute 
# the second partial derivative of the function "sin(x)*cos(y)" with respect to both
#  x and y using the symbolic math library sympy.

# The diff function in sympy is used to calculate the derivative of a given expression. 
# The first argument to the diff function is the expression that we want to differentiate, 
# and the subsequent arguments specify the variables with respect to which we want to 
# differentiate, and the order of differentiation. In this case, x, 2, y, 2 specifies that 
# we want to differentiate the expression twice with respect to x, and then twice with respect to y.

-sin(y)*cos(x)

In [24]:
res = diff(sin(x)*cos(y), x, 2, y, 2)
res

sin(x)*cos(y)

In [25]:
diff(sin(x*y), x, 1, y, 1)

-x*y*sin(x*y) + cos(x*y)

In [26]:
# represents unevaluated derivatives
idiff(x + a + y, [y, a], x)

-Derivative(a, x) - 1

In [27]:
circ = x**2 + y**2 - 4
idiff(circ, y, x)

-x/y

In [28]:
idiff(circ, y, x, 2).simplify()

(-x**2 - y**2)/y**3

### Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [29]:
from numpy import linalg

a = np.array([[4,2,1],[1,3,0],[0,5,4]])
b = np.array([4,12,-3]) 

In [30]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [31]:
#  решение СЛУ -  вектор, содержащий коэффициенты разложения вектора(матрицы) b по столбцам матрицы a,
#  т.е. умножив a на решение, получаем b
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

np.reduce  , accumulate

In [32]:
x = np.arange(1, 6)
x

array([1, 2, 3, 4, 5])

In [42]:
print(np.add.reduce(x)) # 1 + 2 + 3 + 4 + 5
print(np.add.accumulate(x)) # 1, 1 + 2, 1 + 2 + 3, ...)
print(np.sum(x)) # 1 + 2 + 3 + 4 + 5
print(np.cumsum(x)) # 1, 1 + 2, 1 + 2 + 3, ...) 

15
[ 1  3  6 10 15]
15
[ 1  3  6 10 15]


In [43]:
print(np.multiply.reduce(x)) # 1 * 2 * 3 * 4 * 5
print(np.multiply.accumulate(x)) # 1, 1 * 2, 1 * 2 * 3, ...
print(np.prod(x)) # 1 * 2 * 3 * 4 * 5  
print(np.cumprod(x)) # 1, 1 * 2, 1 * 2 * 3, ... 

120
[  1   2   6  24 120]
120
[  1   2   6  24 120]


In [45]:
np.multiply.outer(x, x) #  outer product of two vectors (create a multiplication table)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [47]:
# NumPy’s version of the operation is computed much more quickly:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

74.7 ms ± 1.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
534 µs ± 64.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [51]:
np.random.seed(0) #  set the random seed
M = np.random.random((3, 4))
print(M)
print(M.sum())
print(M.min(axis=0)) #  find the minimum value within each column by specifying axis=0
print(M.max(axis=1)) #  find the maximum value within each row by specifying axis=1

[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]]
7.478282790980994
[0.4236548  0.38344152 0.43758721 0.52889492]
[0.71518937 0.891773   0.96366276]


The `axis` keyword specifies the dimension of the array that will be collapsed,  
rather than the dimension that will be returned.  
So specifying `axis=0` means that the first axis will be collapsed:  
for two-dimensional arrays, this means that values within each column will be aggregated.

| Function Name          | NaN-safe Version          | Description                                      |
|------------------------|---------------------------|--------------------------------------------------|
| np.sum                 | np.nansum                 | Compute sum of elements                         |
| np.prod                | np.nanprod                | Compute product of elements                     |
| np.mean                | np.nanmean                | Compute median of elements                      |
| np.std                 | np.nanstd                 | Compute standard deviation                      |
| np.var                 | np.nanvar                 | Compute variance                                 |
| np.min                 | np.nanmin                 | Find minimum value                               |
| np.max                 | np.nanmax                 | Find maximum value                               |
| np.argmin              | np.nanargmin              | Find index of minimum value                     |
| np.argmax              | np.nanargmax              | Find index of maximum value                     |
| np.median              | np.nanmedian              | Compute median of elements                      |
| np.percentile          | np.nanpercentile          | Compute rank-based statistics of elements       |
| np.any                 | N/A                       | Evaluate whether any elements are true          |
| np.all                 | N/A                       | Evaluate whether all elements are true          |


Broadcasting

In [53]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [54]:
a + b   #  broadcasting -  the smaller array is broadcast across the larger array so that they have compatible shapes

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

| Operator       | Equivalent ufunc   |
| -------------- | ------------------- |
| &              | np.bitwise_and      |
| \|             | np.bitwise_or       |
| ^              | np.bitwise_xor      |
| ~              | np.bitwise_not      |

A AND B and NOT (A OR B) 

In [61]:
np.arange(365) - 172 

array([-172, -171, -170, -169, -168, -167, -166, -165, -164, -163, -162,
       -161, -160, -159, -158, -157, -156, -155, -154, -153, -152, -151,
       -150, -149, -148, -147, -146, -145, -144, -143, -142, -141, -140,
       -139, -138, -137, -136, -135, -134, -133, -132, -131, -130, -129,
       -128, -127, -126, -125, -124, -123, -122, -121, -120, -119, -118,
       -117, -116, -115, -114, -113, -112, -111, -110, -109, -108, -107,
       -106, -105, -104, -103, -102, -101, -100,  -99,  -98,  -97,  -96,
        -95,  -94,  -93,  -92,  -91,  -90,  -89,  -88,  -87,  -86,  -85,
        -84,  -83,  -82,  -81,  -80,  -79,  -78,  -77,  -76,  -75,  -74,
        -73,  -72,  -71,  -70,  -69,  -68,  -67,  -66,  -65,  -64,  -63,
        -62,  -61,  -60,  -59,  -58,  -57,  -56,  -55,  -54,  -53,  -52,
        -51,  -50,  -49,  -48,  -47,  -46,  -45,  -44,  -43,  -42,  -41,
        -40,  -39,  -38,  -37,  -36,  -35,  -34,  -33,  -32,  -31,  -30,
        -29,  -28,  -27,  -26,  -25,  -24,  -23,  -

In [56]:
summer = (np.arange(365) - 172 < 90) & (np.arange(365) - 172 > 0)
summer

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [67]:
summer2 = (np.arange(365) > 172 ) & (np.arange(365) < 262)
# check if two arrays are equal element-wise
np.array_equal(summer, summer2)

True