> Игорь Сорочан DSU-31
# Домашнее задание к занятию `"Линейная алгебра. Матрицы"`


## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [1]:
import numpy as np

In [260]:
### YOUR CODE HERE
a= np.array([range(1,10)]).reshape(3,-1)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [266]:
res1 = a + np.eye(3,3)
res1

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [277]:
res2 = res @ np.array(range(1,4))
res2

array([15., 34., 53.])

In [267]:
np.transpose(res1)

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [268]:
np.linalg.inv(res1)

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01,  2.22044605e-17],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [274]:
### YOUR CODE HERE
m = np.array([[2, 2],
              [1, 3]])
m_ev, m_evs = np.linalg.eig(m)

print(f'Eigenvalue = {m_ev}')
print(f'Eigenvectors:{m_evs}')

Eigenvalue = [1. 4.]
Eigenvectors:[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


In [275]:
m_evs[1] / m_evs[1][0]

array([ 1.        , -1.58113883])

### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2! 

In [224]:
### YOUR CODE HERE

`3x3 identity matrix`

In [276]:
n = 5
cnt = 0
while n > 0:
    a = np.random.randint(3,33,[3,3])
    cnt += 1
    
    if a[0][0]* a[1][1] != a[0][1] * a[1][0]:
        a[2][2] = ( a[0][0]*a[1][2]*a[2][1] - a[0][1]*a[1][2]*a[2][0] - a[0][2]*a[1][0]*a[2][1] + a[0][2]*a[1][1]*a[2][0] +1 ) /\
             (a[0][0]* a[1][1] - a[0][1] * a[1][0])
        if np.linalg.det(a) == 1:
            print(a)
            print(f'det= {np.linalg.det(a)}, matrix_rank= {np.linalg.matrix_rank(a)}')
            n -=1
print(f'Tries # {cnt}')

[[11 14  7]
 [15  9  4]
 [25 32 16]]
det= 1.0, matrix_rank= 3
[[ 9  8 17]
 [32 32 27]
 [31 29 45]]
det= 1.0, matrix_rank= 3
[[16 17 23]
 [ 7  5 10]
 [14 11 20]]
det= 1.0, matrix_rank= 3
[[ 8 11  5]
 [12 14  9]
 [29 25 27]]
det= 1.0, matrix_rank= 3
[[  29   22   20]
 [  32   24   31]
 [  12   13 -118]]
det= 1.0, matrix_rank= 3
Tries # 117337
