## Домашнее задание

### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).


In [1]:
import numpy as np
import scipy.spatial

In [2]:
r = int(input('Введите N (int):') or '9')

In [3]:
new_array = np.array(list(range(r,-1,-1)))
new_array2 = np.array(list(reversed([x for x in range(10)])))
new_array3 = np.array(list(np.arange(r,-1,-1)))
new_array4 = np.array(list(reversed(range(10))))

In [4]:
new_array, new_array2, new_array3, new_array4

(array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]),
 array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]),
 array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]),
 array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))

### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [5]:
semi_eye = np.eye(r+1)*new_array
semi_eye

array([[9., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 8., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 7., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 6., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 5., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 4., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 3., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 2., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
np.diag(np.arange(r, -1, -1), k=0)

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [7]:
np.allclose(np.diag(np.arange(r, -1, -1), k=0), semi_eye)

True

In [8]:
sum([semi_eye[i,i] for i in range(semi_eye.shape[0])])  # сумма строго по диагонали

45.0

In [9]:
print(semi_eye.sum())    # сумма всех элементов матрицы

45.0


In [10]:
s = 0               # сумма строго по диагонали
for j in range(len(semi_eye)):
    s += semi_eye[j,j]
s                

45.0

In [11]:
from functools import reduce  
 # сумма всех элементов матрицы
sum(reduce(lambda x,y: x+y, semi_eye))

45.0

### Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [12]:
from numpy import linalg

a = np.array([[4,2,1],[1,3,0],[0,5,4]])
b = np.array([4,12,-3]) 

In [13]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [14]:
#  решение СЛУ -  вектор, содержащий коэффициенты разложения вектора(матрицы) b по столбцам матрицы a,
#  т.е. умножив a на решение, получаем b
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

### Задание 4

In [15]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, покупках которого известно следующее:

In [16]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])


Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats




In [17]:
similar = []        # список с Cosine similarity
similar2 = []

In [18]:
%%timeit
# compute Cosine similarity using SCIPY


for r in range(users_stats.shape[0]):
    # Cosine similarity =  1 - cosine distance.  https://en.wikipedia.org/wiki/Cosine_similarity            
    # https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cosine.html
    similar.append( 1- scipy.spatial.distance.cosine(users_stats[r],next_user_stats)  )

# print(similar)


744 µs ± 60.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [19]:
%%timeit
# реализация только инструментами Numpy в 3 раза быстрее, чем SCIPY

for r in range(users_stats.shape[0]):
    dotprod = np.dot(users_stats[r],next_user_stats)
    euclidprod = np.sqrt(  sum(users_stats[r]**2)  *  sum(next_user_stats**2)  )
    similar2.append( dotprod / euclidprod  )
# print(similar2)


187 µs ± 3.36 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [20]:
print(f'Статистики идентичны -{np.allclose( similar2, similar  )}')
ind = similar.index(max(similar))
print(f'Клиент магазина  {users_stats[ind]} с индексом {7}  имеет  наибольшее косинусное сходство ({max(similar):.3})' )
print(f'c новым клиентом {next_user_stats} ')

Статистики идентичны -True
Клиент магазина  [0 1 1 0 0 0] с индексом 7  имеет  наибольшее косинусное сходство (0.949)
c новым клиентом [0 1 2 0 0 0] 


### Операции с матрицами

In [24]:
import numpy as np

a = np.array([[3],[4],[2]])  # следить, чтобы бы именно 2-мерные массивы
b = np.array([5,-2,3]).reshape(1,3)
print('матрицы   :\n',a, b )
print('b@a   \n',b@a)
print('a@b   \n',a@b)

print('sum(a@b)  \n',sum(a@b))
sum(sum(a@b))+b@a

матрицы   :
 [[3]
 [4]
 [2]] [[ 5 -2  3]]
b@a   
 [[13]]
a@b   
 [[15 -6  9]
 [20 -8 12]
 [10 -4  6]]
sum(a@b)  
 [ 45 -18  27]


array([[67]])

In [22]:
import sympy as sp
from sympy import Matrix

x = sp.symbols("x")
A = Matrix([[5, -3, x], [1, 1, -2], [2, x + 2, -1]])
det = A.det()
print(det)
print(sp.solve(det))
print(sum(sp.solve(det)))

x**2 + 10*x + 24
[-6, -4]
-10


In [23]:
import numpy as np

a = np.array([3,4,2]).reshape(3,1)

b = np.array([5,-2,3]).reshape(1,3)

print(a@b)

print(b@a)

[[15 -6  9]
 [20 -8 12]
 [10 -4  6]]
[[13]]


In [34]:
a = np.array([3,4,2])
b = np.array([5,-2,3])


In [38]:
print(a,b)

[[3]
 [4]
 [2]] [[ 5 -2  3]]


In [36]:
print('b@a   \n',b@a)
print('a@b   \n',a@b)

b@a   
 13
a@b   
 13


In [39]:
a = a.reshape(3,1)
b = b.reshape(1,3)
print(a,b)

[[3]
 [4]
 [2]] [[ 5 -2  3]]


In [41]:
print('b@a   \n',b@a)
print('a@b   \n',a@b)

b@a   
 [[13]]
a@b   
 [[15 -6  9]
 [20 -8 12]
 [10 -4  6]]


In [52]:
a@b@a == a@[[13]]

array([[ True],
       [ True],
       [ True]])