In [5]:
import sympy as sp
from sympy import Matrix
import pandas as pd

x = sp.symbols("x")
A = Matrix([[5, -3, x], [1, 1, -2], [2, x + 2, -1]])
det = A.det()
print(det)
print(sp.solve(det))
print(sum(sp.solve(det)))

x**2 + 10*x + 24
[-6, -4]
-10


In [1]:
import numpy as np
# matrix product
a = np.array([[3],[4],[2]])
b = np.array([5,-2,3])
b= b.reshape(1,3)  # [5,-2,3] -> [[ 5 -2  3]]
print(a,a.shape,'\n\n',b,b.shape,'\n')
print(a,b)
print(b@a)
print(a@b)


[[3]
 [4]
 [2]] (3, 1) 

 [[ 5 -2  3]] (1, 3) 

[[3]
 [4]
 [2]] [[ 5 -2  3]]
[[13]]
[[15 -6  9]
 [20 -8 12]
 [10 -4  6]]


In [ ]:
# Замена значений столбца на предлагаемые в массиве 
# Заменяем пол и курение на числа
df['sex']=df['sex'].map({'male':1, 'female':0})
df['smoker']=df['smoker'].map({'yes':1,'no':0})

"\n# MAP  Замена значений столбца на предлагаемые в массиве\n# Заменяем пол и курение на числа\ndf['sex']=df['sex'].map({'male':1, 'female':0})\ndf['smoker']=df['smoker'].map({'yes':1,'no':0})\n"

In [ ]:
# get_dummies   Convert categorical variable into dummy/indicator variables.
# Заменяем столбец  region на набор отдельных столбцов, состоящих из уникальных значений region  (is_southwest, is_southeast и тп)  ака ТРАНСПОНИРОВАНИЕ
df = pd.get_dummies(df, columns=['region'])

"\n# get_dummies   Convert categorical variable into dummy/indicator variables.\n# Заменяем столбец  region на набор отдельных столбцов, состоящих из уникальных значений region  (is_southwest, is_southeast и тп)  ака ТРАНСПОНИРОВАНИЕ\ndf = pd.get_dummies(df, columns=['region'])\n"

Calculates matrix determinant

In [ ]:
%%time
import sympy as sp
from sympy import Matrix

x = sp.symbols("x")
A = Matrix([[7,10, 5,6,7], [8, 11,3,7,10], [5, 6, 6,5,7],[5,7,2,4,5],[3,5,5,2,0]])
#. Calculates matrix determinant
det = A.det()
print(det)

5
CPU times: user 7.13 ms, sys: 0 ns, total: 7.13 ms
Wall time: 7.13 ms


$$
y=a+bx+\epsilon \\
\epsilon \sim \mathcal{N}(0,\,\sigma^{2})
$$

it means that

$$
p(\epsilon)=\frac{1}{\sqrt{2 \pi \sigma^2}} e^{-\frac{\epsilon^2}{2\sigma^2}}.
$$


In [11]:
%%time
import sympy as sp
from sympy import Matrix

x = sp.symbols("x")
A = Matrix([[3,0,-1], [2,-2,3], [-1,2,5]])
#. Calculates matrix determinant
det = A.det()
print(det)

print(A.inv()*50)


-50
Matrix([[16, 2, 2], [13, -14, 11], [-2, 6, 6]])
CPU times: user 2.3 ms, sys: 0 ns, total: 2.3 ms
Wall time: 2.26 ms


In [ ]:
dir(Matrix)

In [8]:
?Matrix.inv

In [ ]:
%%writefile foo.py
print('Hello world')

Writing foo.py


In [ ]:
%run foo

Hello world


In [ ]:
%%bash
echo "hello from $BASH"

hello from /bin/bash


In [ ]:
#Finding all subsets of a set in one line
from itertools import combinations, permutations
print(list(combinations([1, 2, 3, 4], 2)), end='')
print('\n\n')
print(list(permutations([1, 2, 3, 4], 2)))

[(1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)]


[(1, 2), (1, 3), (1, 4), (2, 1), (2, 3), (2, 4), (3, 1), (3, 2), (3, 4), (4, 1), (4, 2), (4, 3)]


In [ ]:
!python --version

Python 3.7.14


In [ ]:
dir(__builtin__)

In [ ]:
? print

In [ ]:
'''
range() сам по себе это отдельный тип данных, он не итератор и не генератор. Нельзя применить next() просто так к range(), 
необходимо сначала преобразовать к итератору с помощью функции iter() и уже затем мы можем пройтись по последовательность из range(). 
'''

r = range(0,10,1)
i = iter (r)
print(next(i))
print(next(i))
print(next(i))

print (r, '|', i)

0
1
2
range(0, 10) | <range_iterator object at 0x7fecfffa58a0>


In [ ]:
len(r)

10

In [ ]:
l = list(r)
print(l,type(l), sep=' | ')

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] | <class 'list'>


In [ ]:
for x in range(5):
  print(x)

0
1
2
3
4


In [ ]:
l = list ((range(10)))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# переворачиваем список
#%%timeit
l3=l[::-1]
l3

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [ ]:
l3=list(reversed(l))
l3

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [ ]:
#  slice as an object
slice_3_4 = slice(2,4)
a=l3[slice_3_4]
b=l[slice_3_4]
print(slice_3_4, type(slice_3_4), a, b, sep=' | ')

slice(2, 4, None) | <class 'slice'> | [7, 6] | [2, 3]


In [ ]:
array = ['aa','bbbbb', 'c', 'ddd']
string = '_'.join(array)
string

'aa_bbbbb_c_ddd'

In [ ]:
l = list (array) 
l.append("Bang!")
print (l , sorted(l, reverse = True), sep=' - ')

['aa', 'bbbbb', 'c', 'ddd', 'Bang!'] - ['ddd', 'c', 'bbbbb', 'aa', 'Bang!']


In [ ]:
l.pop(-1) # delete list item with index (-1) and return it 

'Bang!'

In [ ]:
l

['aa', 'bbbbb', 'c', 'ddd']

In [ ]:
#. sort on string lenght

print(sorted(l, key = lambda x: len(x), reverse = False))
print(sorted(l, key = lambda x: len(x), reverse = True))

['c', 'aa', 'ddd', 'bbbbb']
['bbbbb', 'ddd', 'aa', 'c']


#    sorted - не изменяет объект
#    sort   - изменяет

In [ ]:
def comparator(string):
  return len(string)

In [ ]:
comparator(l)

4

In [ ]:
sorted(l, key = comparator)

['c', 'aa', 'ddd', 'bbbbb']

In [ ]:
l.sort() # sort  -change the object
l

['aa', 'bbbbb', 'c', 'ddd']

In [ ]:
items =      [1,3,2,7,33,4,5,9,3,17,999]
shuffled_items = [9,7,4,999,5,3,1]
print(items)
print(shuffled_items)

[1, 3, 2, 7, 33, 4, 5, 9, 3, 17, 999]
[9, 7, 4, 999, 5, 3, 1]


In [ ]:
#         сортируем  по          индексу в items
# get shuffled_items entry and seek it's index in items. I no -> error
shuffled_items.sort(key= lambda x: items.index(x))
print(items)
print(shuffled_items)

[1, 3, 2, 7, 33, 4, 5, 9, 3, 17, 999]
[1, 3, 7, 4, 5, 9, 999]


In [ ]:
methods = dir(__builtins__)  # сканируем __builtins__
print (type(methods), '\n')
#The enumerate object yields pairs containing a count (from start, which
#defaults to zero) and a value yielded by the iterable argument.

for num, method  in enumerate(methods):  # выводим пронумерованный список methods
  if num % 25 == 1:
    print(num, method)

<class 'list'> 

1 AssertionError
26 ImportWarning
51 StopAsyncIteration
76 __loader__
101 enumerate
126 map
151 tuple


In [ ]:
for num, method  in enumerate(methods):  # выводим пронумерованный список methods
  if num % 25 == 1:
    print(num, method)

1 AssertionError
26 ImportWarning
51 StopAsyncIteration
76 __loader__
101 enumerate
126 map
151 tuple


In [ ]:
enum = list(enumerate (methods)) #  список из пар  num, method
zip_enum = list(zip (range(0,len(methods)),
                    methods))  # zip  склеивает  номер по порядку и methods
print( enum == zip_enum)

True


In [ ]:
enum = list(enumerate (methods, start = 0)) #  список из пар  index, value (method)
#  zip склеивает  две последовательности (range и methods). Until the shortest len
zip_enum = list(zip(range(0,len(methods)) , methods ))  
print( enum == zip_enum)

True


In [ ]:
first = 'a b c d e f g'.split(' ')

zip_style = zip(range(0, len(first)), first)

print(list(zip_style))

# Отличие итераторов (функции enumerate и zip создают объекты итераторы) от листа в том, что итераторы поддерживают лишь единственную итерацию по себе,
# по ее истечении они оказываются полностью перечисленными 

print(list(zip_style))  # здесь уже итератор выполнен

[(0, 'a'), (1, 'b'), (2, 'c'), (3, 'd'), (4, 'e'), (5, 'f'), (6, 'g')]
[]


In [ ]:
? enumerate

In [ ]:
from scipy.optimize.minpack import transpose
#вывести список из 100 чисел
", ".join(  [str(x) for x in range(100)]  )  # это не список, а строка

'0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99'

In [ ]:
 a = [str(x) for x in range(100)]
 a[:9]

['0', '1', '2', '3', '4', '5', '6', '7', '8']

In [ ]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [ ]:
t = 'abc', 12, 12.9
t2 = 12.,
print(t,type(t),'\n',t2,type(t2))
print(t2[0],  type(t2[0]))

('abc', 12, 12.9) <class 'tuple'> 
 (12.0,) <class 'tuple'>
12.0 <class 'float'>


In [ ]:
l=['abg.asdas', 'dsfasd.sdf.sdf','sdf...asd','asdf.asdfa','sdfas']
# вывести строки , где > 2 '.'
print ([x for x in l if x.count('.') > 2 ])
# вывести  список строк и кол-во точек в них
list(zip([x.count('.') for x in l ], l))

['sdf...asd']


[(1, 'abg.asdas'),
 (2, 'dsfasd.sdf.sdf'),
 (3, 'sdf...asd'),
 (1, 'asdf.asdfa'),
 (0, 'sdfas')]

In [ ]:
s1 = set(range(12))
s2 = set (range(7,20))
print(s1.difference(s2))
print(s2.difference(s1))
print(s1.intersection(s2))
print(s1.union(s2))

{0, 1, 2, 3, 4, 5, 6}
{12, 13, 14, 15, 16, 17, 18, 19}
{7, 8, 9, 10, 11}
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19}


In [ ]:
d = { a:a**2 for a in range(1,11)}
d

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}

In [ ]:
text="Hello"
print(text[4:100])

o


In [ ]:
file = open("out.txt", "w")

for i in range(5):

    file.write(str(i))

file.close()

file = open("out.txt", "w")

for i in range(5, 10):

    file.write(str(i))

file.close()

In [ ]:
vec = [[1,2,3], [4,5,6], [7,8,9]]
[num for elem in vec for num in elem]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
vec = [[1,2,3], [4,5,6], [7,8,9]]

for elem in vec:
   for num in elem:
     print(num)

1
2
3
4
5
6
7
8
9


In [ ]:
matrix = [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12],
    ]
#                           for   i = 0 1 2 3 4
# [           iter rows   
# yield i-th 
# elem from row            ]    
# [ ]  forms the row
[[row[i] for row in matrix] for i in range(4)]

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [ ]:
for row in matrix:
  print (row )

[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]


In [ ]:
from functools import reduce
# вывод строки из списка
methods = dir(__builtin__)
''.join(    reduce(lambda x,y: x + ', ' + y , methods )   )      

'ArithmeticError, AssertionError, AttributeError, BaseException, BlockingIOError, BrokenPipeError, BufferError, BytesWarning, ChildProcessError, ConnectionAbortedError, ConnectionError, ConnectionRefusedError, ConnectionResetError, DeprecationWarning, EOFError, Ellipsis, EnvironmentError, Exception, False, FileExistsError, FileNotFoundError, FloatingPointError, FutureWarning, GeneratorExit, IOError, ImportError, ImportWarning, IndentationError, IndexError, InterruptedError, IsADirectoryError, KeyError, KeyboardInterrupt, LookupError, MemoryError, ModuleNotFoundError, NameError, None, NotADirectoryError, NotImplemented, NotImplementedError, OSError, OverflowError, PendingDeprecationWarning, PermissionError, ProcessLookupError, RecursionError, ReferenceError, ResourceWarning, RuntimeError, RuntimeWarning, StopAsyncIteration, StopIteration, SyntaxError, SyntaxWarning, SystemError, SystemExit, TabError, TimeoutError, True, TypeError, UnboundLocalError, UnicodeDecodeError, UnicodeEncodeErro

In [ ]:
from collections import defaultdict, Counter

# lets count letters in a list
counter = Counter()
for word in dir(__builtin__):
    for letter in word:
        counter[letter] += 1  # или .update(value)
    
print(counter)

Counter({'r': 227, 'e': 138, 'o': 137, 'n': 103, 't': 101, 'i': 92, 'a': 66, 's': 61, 'E': 57, 'c': 53, 'l': 47, '_': 47, 'p': 42, 'd': 41, 'm': 31, 'u': 30, 'y': 23, 'g': 22, 'b': 20, 'x': 16, 'I': 14, 'h': 12, 'f': 11, 'W': 11, 'v': 9, 'F': 8, 'N': 8, 'A': 7, 'P': 7, 'R': 7, 'S': 7, 'U': 7, 'k': 6, 'O': 6, 'D': 6, 'T': 6, 'B': 5, 'C': 5, '1': 4, 'L': 3, 'w': 3, 'K': 2, 'M': 2, 'z': 2, 'G': 1, 'V': 1, 'Z': 1, 'Y': 1, 'H': 1, '4': 1, '0': 1, '3': 1, 'j': 1})


In [ ]:
arg ='__builtin__'
set(dir(arg)) - set(dir(object))

{'__add__',
 '__contains__',
 '__getitem__',
 '__getnewargs__',
 '__iter__',
 '__len__',
 '__mod__',
 '__mul__',
 '__rmod__',
 '__rmul__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill'}

# Unzip

In [ ]:
# unzip
!ls # проверяем, что здесь лежит somefile.rar
get_ipython().system_raw("unrar x somefile.rar")

# Search through ipynb files

In [ ]:
!ls

### cmd

In [2]:
# !grep -o -r --include  \*.ipynb SQL ipynb
# search SQL in \*.ipynb
grep -o -r --include  \*.ipynb SQL ipynb

'grep' is not recognized as an internal or external command,
operable program or batch file.


# search from  notebook

In [5]:
import glob

# pattern = '../**/*.ipynb'
pattern = '*.ipynb'

# q = 'SQL'
q = 'try'

for filepath in glob.iglob(pattern, recursive=True):
    with open(filepath, encoding='UTF-8') as file:
        # print(file)
        s = file.read()
        if (s.find( q ) > -1):
            print(filepath)

ABD-22 Total HW.ipynb
DLS  simpsons_baseline.ipynb
DLS Python Base.ipynb
lecture_04_andas.ipynb
Netlogy ERRORS_DATES .ipynb
Netlogy ERRORS_DATES HW.ipynb
Netology Pandas HW_SQL.ipynb
Netology Pandas_basics.ipynb
Netology Pandas_functions_groupby.ipynb
Netology Pandas_JOIN_HW.ipynb
Netology Pandas_JOIN_SQL_HW .ipynb
Netology PySpark Лекция 7.ipynb
Netology Python list dict.ipynb
Netology Python _Bases2.ipynb
Netology Python_7_ERRORS_DATETIME.ipynb
Netology_REGEX_practice.ipynb
Netology_SCRAPING PARSING.ipynb
Pandas_MULTIindex.ipynb
Python MathPlotLib VIZ.ipynb
Python PARSING.ipynb
Python SQL.ipynb
Python_9_Numpy Matrix.ipynb
Python_Tricks.ipynb


### целочисленное деление и остаток от деления 

In [29]:
a, b = -9, -5
a - a//b * b
print (a % b)
a % b == a - a//b * b

-4


True

In [37]:
2**3**2 == 2**(3**2) == 2**9 == 512

True

## python reserved *keywords*

In [15]:
help('keywords')


Here is a list of the Python keywords.  Enter any keyword to get more help.

False               class               from                or
None                continue            global              pass
True                def                 if                  raise
and                 del                 import              return
as                  elif                in                  try
assert              else                is                  while
async               except              lambda              with
await               finally             nonlocal            yield
break               for                 not                 



In [6]:
# ввод целого числа
d1, d2, d3, d4, d5 = map(int, input().split())

ValueError: not enough values to unpack (expected 5, got 0)