In [99]:
import pandas as pd
import numpy as np

In [100]:
# Замена значений столбца на предлагаемые в массиве 
# Заменяем пол и курение на числа
df = pd.DataFrame(np.array([['Ann','female','yes'],
                ['Boris','male','no'],
                ['Kate','female','yes']]),
                    columns= ['Name', 'sex', 'smoker'])
df

Name     sex smoker
0    Ann  female    yes
1  Boris    male     no
2   Kate  female    yes

In [101]:
# get_dummies   Convert categorical variable into dummy/indicator variables.

df = pd.get_dummies(df, columns=['sex'])
df

Name smoker  sex_female  sex_male
0    Ann    yes           1         0
1  Boris     no           0         1
2   Kate    yes           1         0

In [102]:
# df['sex2']=df['sex'].map({'male':1, 'female':0})
df['smoker2']=df['smoker'].map({'yes':1,'no':0})
df

Name smoker  sex_female  sex_male  smoker2
0    Ann    yes           1         0        1
1  Boris     no           0         1        0
2   Kate    yes           1         0        1

In [103]:
import pandas as pd

# Create a sample dataframe with a categorical column 'color'
df = pd.DataFrame({'color': ['red', 'green', 'blue', 'red']})

# Use get_dummies to convert the 'color' column into one-hot encoded columns
df_encoded = pd.get_dummies(df['color'])
df_encoded

blue  green  red
0     0      0    1
1     0      1    0
2     1      0    0
3     0      0    1

In [104]:

# Concatenate the original dataframe with the one-hot encoded columns
df_concat = pd.concat([df, df_encoded], axis=1)

print(df_concat)


   color  blue  green  red
0    red     0      0    1
1  green     0      1    0
2   blue     1      0    0
3    red     0      0    1


### `LATEX` in Markdown

$$
y=a+bx+\epsilon \\
\epsilon \sim \mathcal{N}(0,\,\sigma^{2})
$$

it means that

$$
p(\epsilon)=\frac{1}{\sqrt{2 \pi \sigma^2}} e^{-\frac{\epsilon^2}{2\sigma^2}}.
$$


In [108]:
#Finding all subsets (of given length) of a set in one line
from itertools import combinations, permutations
print(list(combinations([1, 2, 3, 4], 2) ), end='')
print('\n\n')
print(list(permutations([1, 2, 3, 4], 3) ) )

[(1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)]


[(1, 2, 3), (1, 2, 4), (1, 3, 2), (1, 3, 4), (1, 4, 2), (1, 4, 3), (2, 1, 3), (2, 1, 4), (2, 3, 1), (2, 3, 4), (2, 4, 1), (2, 4, 3), (3, 1, 2), (3, 1, 4), (3, 2, 1), (3, 2, 4), (3, 4, 1), (3, 4, 2), (4, 1, 2), (4, 1, 3), (4, 2, 1), (4, 2, 3), (4, 3, 1), (4, 3, 2)]


In [110]:
# dir(__builtin__)

In [111]:
# ? print

In [1]:
'''
range() сам по себе это отдельный тип данных, он не итератор и не генератор. Нельзя применить next() просто так к range(), 
необходимо сначала преобразовать к итератору с помощью функции iter() и уже затем мы можем пройтись по последовательность из range(). 
'''

r = range(0,10,1)
i = iter (r)
print(next(i))
print(next(i))
print(next(i))

print (r, '|', i)

0
1
2
range(0, 10) | <range_iterator object at 0x7f78881e6030>


In [2]:
len(r)

10

In [114]:
l = list(r)
print(l,type(l), sep=' | ')

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] | <class 'list'>


In [115]:
for x in range(5):
  print(x)

0
1
2
3
4


In [116]:
l = list ((range(10)))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [117]:
# переворачиваем список
#%%timeit
l3=l[::-1]
l3

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [118]:
l3=list(reversed(l))
l3

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [119]:
#  slice as an object
slice_3_4 = slice(2,4)
a=l3[slice_3_4]
b=l[slice_3_4]
print(slice_3_4, type(slice_3_4), a, b, sep=' | ')

slice(2, 4, None) | <class 'slice'> | [7, 6] | [2, 3]


In [120]:
array = ['aa','bbbbb', 'c', 'ddd']
string = '_'.join(array)
string

'aa_bbbbb_c_ddd'

In [121]:
l = list (array) 
l.append("Bang!")
print (l , sorted(l, reverse = True), sep=' - ')

['aa', 'bbbbb', 'c', 'ddd', 'Bang!'] - ['ddd', 'c', 'bbbbb', 'aa', 'Bang!']


In [122]:
l.pop(-1) # delete list item with index (-1) and return it 

'Bang!'

In [123]:
l

['aa', 'bbbbb', 'c', 'ddd']

In [124]:
len(l)

4

In [125]:
# sort on string length

print(sorted(l, key = lambda x: len(x), reverse = False))
print(sorted(l, key = lambda x: len(x), reverse = True))

['c', 'aa', 'ddd', 'bbbbb']
['bbbbb', 'ddd', 'aa', 'c']


#    sorted - не изменяет объект
#    sort   - изменяет

In [126]:
def comparator(string):
  return len(string)

In [127]:
comparator(l)

4

In [128]:
sorted(l, key = comparator)

['c', 'aa', 'ddd', 'bbbbb']

In [129]:
l.sort() # sort  -change the object
l

['aa', 'bbbbb', 'c', 'ddd']

In [130]:
items =      [1,3,2,7,33,4,5,9,3,17,999]
shuffled_items = [9,7,4,999,5,3,1]
print(items)
print(shuffled_items)

[1, 3, 2, 7, 33, 4, 5, 9, 3, 17, 999]
[9, 7, 4, 999, 5, 3, 1]


In [131]:
#         сортируем  по          индексу в items
# get shuffled_items entry and seek it's index in items. I no -> error
shuffled_items.sort(key= lambda x: items.index(x))
print(items)
print(shuffled_items)

[1, 3, 2, 7, 33, 4, 5, 9, 3, 17, 999]
[1, 3, 7, 4, 5, 9, 999]


In [132]:
methods = dir(__builtins__)  # сканируем __builtins__
print (type(methods), '\n')
#The enumerate object yields pairs containing a count (from start, which
#defaults to zero) and a value yielded by the iterable argument.

for num, method  in enumerate(methods):  # выводим пронумерованный список methods
  if num % 25 == 1:
    print(num, method)

<class 'list'> 

1 AssertionError
26 ImportWarning
51 StopAsyncIteration
76 __loader__
101 divmod
126 locals
151 super


In [133]:
for num, method  in enumerate(methods):  # выводим пронумерованный список methods
  if num % 25 == 1:
    print(num, method)

1 AssertionError
26 ImportWarning
51 StopAsyncIteration
76 __loader__
101 divmod
126 locals
151 super


In [134]:
enum = list(enumerate (methods)) #  список из пар  num, method
zip_enum = list(zip (range(0,len(methods)),
                    methods))  # zip  склеивает  номер по порядку и methods
print( enum == zip_enum)

True


In [135]:
enum = list(enumerate (methods, start = 0)) #  список из пар  index, value (method)
#  zip склеивает  две последовательности (range и methods). Until the shortest len
zip_enum = list(zip(range(0,len(methods)) , methods ))  
print( enum == zip_enum)

True


In [136]:
first = 'a b c d e f g'.split(' ')

zip_style = zip(range(0, len(first)), first)

print(list(zip_style))

# Отличие итераторов (функции enumerate и zip создают объекты итераторы) от листа в том, что итераторы поддерживают лишь единственную итерацию по себе,
# по ее истечении они оказываются полностью перечисленными 

print(list(zip_style))  # здесь уже итератор выполнен

[(0, 'a'), (1, 'b'), (2, 'c'), (3, 'd'), (4, 'e'), (5, 'f'), (6, 'g')]
[]


In [137]:
? enumerate

Init signature:  enumerate(iterable, start=0)
Docstring:     
Return an enumerate object.

  iterable
    an object supporting iteration

The enumerate object yields pairs containing a count (from start, which
defaults to zero) and a value yielded by the iterable argument.

enumerate is useful for obtaining an indexed list:
    (0, seq[0]), (1, seq[1]), (2, seq[2]), ...
Type:           type
Subclasses:     


In [138]:
from scipy.optimize.minpack import transpose
#вывести список из 100 чисел
", ".join(  [str(x) for x in range(100)]  )  # это не список, а строка

'0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99'

In [139]:
 a = [str(x) for x in range(100)]
 a[:9]

['0', '1', '2', '3', '4', '5', '6', '7', '8']

In [140]:
import this

In [141]:
t = 'abc', 12, 12.9
t2 = 12.,
print(t,type(t),'\n',t2,type(t2))
print(t2[0],  type(t2[0]))

('abc', 12, 12.9) <class 'tuple'> 
 (12.0,) <class 'tuple'>
12.0 <class 'float'>


In [142]:
l=['abg.asdas', 'dsfasd.sdf.sdf','sdf...asd','asdf.asdfa','sdfas']
# вывести строки , где > 2 '.'
print ([x for x in l if x.count('.') > 2 ])
# вывести  список строк и кол-во точек в них
list(zip([x.count('.') for x in l ], l))

['sdf...asd']


[(1, 'abg.asdas'),
 (2, 'dsfasd.sdf.sdf'),
 (3, 'sdf...asd'),
 (1, 'asdf.asdfa'),
 (0, 'sdfas')]

In [143]:
s1 = set(range(12))
s2 = set (range(7,20))
print(s1.difference(s2)) # Return the difference of two or more sets as a new set.
print(s2.difference(s1))
print(s1.intersection(s2)) # Return the intersection of two sets as a new set.
print(s1.union(s2)) # Return the union of sets as a new set.

{0, 1, 2, 3, 4, 5, 6}
{12, 13, 14, 15, 16, 17, 18, 19}
{7, 8, 9, 10, 11}
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19}


In [144]:
d = { a:a**2 for a in range(1,11)}
d

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}

In [145]:
text="Hello"
print(text[4:100])

o


In [146]:
file = open("out.txt", "w")

for i in range(5):

    file.write(str(i))

file.close()

file = open("out.txt", "w")

for i in range(5, 10):

    file.write(str(i))

file.close()

In [147]:
vec = [[1,2,3], [4,5,6], [7,8,9]]
[elem      for sublist in vec     for elem in sublist]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

The outer loop `for sublist in vec` iterates over each element `sublist` in the list `vec`.

The inner loop `for elem in sublist` iterates over each element `elem` in the current `sublist`.

For each iteration of the inner loop, the expression `elem` is appended to the final list, which is constructed using the list comprehension syntax.

After both loops have completed, the final list comprehension will contain all elements from vec, flattened into a 1-dimensional list.

In [148]:
[elem for elem in vec]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [149]:
vec = [[1,2,3], [4,5,6], [7,8,9]]

for elem in vec:
   for num in elem:
     print(num)

1
2
3
4
5
6
7
8
9


In [150]:
matrix = [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12],
    ]

[[sublist[i] for sublist in matrix] for i in range(len(matrix[0]) )]

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [151]:
for sublist in matrix:
  print (sublist )

[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]


In [152]:
from functools import reduce
# вывод строки из списка c sep=', '
methods = dir(__builtin__)
# reduce() Apply a function of two arguments cumulatively to 
# the items of a sequence or iterable, from left to right, 
# so as to reduce the iterable to a single
''.join(    reduce(lambda x,y: x + ', ' + y , methods )   )      

'ArithmeticError, AssertionError, AttributeError, BaseException, BlockingIOError, BrokenPipeError, BufferError, BytesWarning, ChildProcessError, ConnectionAbortedError, ConnectionError, ConnectionRefusedError, ConnectionResetError, DeprecationWarning, EOFError, Ellipsis, EnvironmentError, Exception, False, FileExistsError, FileNotFoundError, FloatingPointError, FutureWarning, GeneratorExit, IOError, ImportError, ImportWarning, IndentationError, IndexError, InterruptedError, IsADirectoryError, KeyError, KeyboardInterrupt, LookupError, MemoryError, ModuleNotFoundError, NameError, None, NotADirectoryError, NotImplemented, NotImplementedError, OSError, OverflowError, PendingDeprecationWarning, PermissionError, ProcessLookupError, RecursionError, ReferenceError, ResourceWarning, RuntimeError, RuntimeWarning, StopAsyncIteration, StopIteration, SyntaxError, SyntaxWarning, SystemError, SystemExit, TabError, TimeoutError, True, TypeError, UnboundLocalError, UnicodeDecodeError, UnicodeEncodeErro

In [153]:
from collections import defaultdict, Counter

# lets count letters in a list
counter = Counter()
for word in dir(__builtin__):
    for letter in word:
        counter[letter] += 1  # или .update(value)
    
print(counter)

Counter({'r': 227, 'e': 138, 'o': 137, 'n': 104, 't': 100, 'i': 92, 'a': 67, 's': 60, 'E': 57, 'c': 52, 'l': 48, '_': 47, 'p': 42, 'd': 40, 'm': 31, 'u': 30, 'y': 23, 'g': 22, 'b': 20, 'x': 16, 'I': 14, 'h': 12, 'f': 11, 'W': 11, 'v': 9, 'F': 8, 'N': 8, 'A': 7, 'P': 7, 'R': 7, 'S': 7, 'U': 7, 'k': 6, 'O': 6, 'D': 6, 'T': 6, 'B': 5, 'C': 5, 'L': 3, 'w': 3, '1': 3, 'K': 2, 'M': 2, '0': 2, 'z': 2, 'G': 1, 'V': 1, 'Z': 1, 'Y': 1, 'H': 1, '4': 1, '2': 1, 'j': 1})


In [154]:
arg ='__builtin__'
print(len(set(dir(arg))), len(set(dir(object))), len(set(dir(arg)) - set(dir(object))))
# print out distinct '__builtin__'  atribbutes
print(set(dir(arg)) - set(dir(object)))

80 23 57
{'isalnum', 'zfill', 'startswith', 'isupper', 'index', 'rstrip', 'isspace', '__len__', 'count', 'endswith', 'ljust', 'splitlines', 'split', 'isidentifier', '__rmul__', 'partition', '__getnewargs__', 'title', 'isprintable', '__rmod__', 'rjust', 'lower', 'find', '__getitem__', 'casefold', 'removesuffix', 'swapcase', '__contains__', 'istitle', 'strip', 'isdecimal', '__add__', 'upper', 'lstrip', 'rsplit', 'expandtabs', 'translate', 'isalpha', '__mul__', 'rpartition', 'format', 'center', 'removeprefix', 'isascii', 'join', 'rfind', '__mod__', 'capitalize', 'isdigit', 'isnumeric', 'format_map', '__iter__', 'maketrans', 'rindex', 'replace', 'encode', 'islower'}


# Search through ipynb files

In [155]:
!ls

ABD_22_LABa.ipynb
ABD_22_LABa_Kuzmin_Pandas.ipynb
ABD_22_Total_HW.ipynb
COVID-19_visualization.ipynb
Constraint_Programming.ipynb
DLS_Python_Base.ipynb
DLS_simpsons_baseline.ipynb
DateTimeTimeZone.ipynb
Decorator.ipynb
ERRORS_DATES_.ipynb
ERRORS_DATES_HW.ipynb
ML_linear_polynomial_regression.ipynb
ML_log_regression_SVM.ipynb
MathPlotLib_VIZ.ipynb
MathPlotLib_VIZ2.ipynb
MathPlotLib_VIZ3.ipynb
Numpy_HW.ipynb
PARSING.ipynb
Pandas_Change_value_on_condition.ipynb
Pandas_ESSENTIALS.ipynb
Pandas_HW_SQL.ipynb
Pandas_HW_funcs_group.ipynb
Pandas_JOIN.ipynb
Pandas_JOIN_HW.ipynb
Pandas_JOIN_SQL_HW_.ipynb
Pandas_MULTIindex.ipynb
Pandas_PIVOT_and_PYMYSTEM.ipynb
Pandas_basics.ipynb
Pandas_functions_groupby.ipynb
Pandas_lecture_04.ipynb
Pandas_pivot_and_str.ipynb
Pandas_presentation_mode.ipynb
Pandas_vs_set_and_dict.ipynb
Practice_AB
PySpark_Лекция_7.ipynb
Python_7_ERRORS_DATETIME.ipynb
Python_Bases2.ipynb
Python_CLASSES.ipynb
Python_Datatypes_LOOPs.ipynb
Python_EDA.ipynb
Python_FILES_Read_Write_and_p

### cmd

In [161]:
# !grep -o -r --include  \*.ipynb SQL ipynb
# search SQL in \*.ipynb
!grep -o -r --include  \*.ipynb SQL ipynb

### целочисленное деление и остаток от деления 

In [162]:
a, b = -9, -5
a - a//b * b
print (a % b)
a % b == a - a//b * b

-4


True

In [158]:
2**3**2 == 2**(3**2) == 2**9 == 512

True

## python reserved *keywords*

In [159]:
help('keywords')


Here is a list of the Python keywords.  Enter any keyword to get more help.

False               break               for                 not
None                class               from                or
True                continue            global              pass
__peg_parser__      def                 if                  raise
and                 del                 import              return
as                  elif                in                  try
assert              else                is                  while
async               except              lambda              with
await               finally             nonlocal            yield



#### `Input a series of integers`

In [160]:
# ввод только целого числа
inq = [int(float(x) ) for x in input().split(' ')]
inq

[1, 2]

##### `Steps to select only those dataframe rows, which contain any NaN value `
* **Step 1**: 
Call the `isnull()` function on dataframe like `df.isnull()`. It will return a same sized bool dataframe containing only `True or False` values. True value indicates that there is a NaN at the corresponding position in the original dataframe and False indicates a Non-NaN value.
* **Step 2**: Then call the `any(axis=1)` function on the bool dataframe like, `df.isnull().any(axis=1)`. The any() function looks for any True value along the given axis. If `axis==1`, then it will look along the columns for each row. It means, for each row it will check all the column values and reduce it to a single value. For a row, if any column contains the NaN, then the reduced value for that row will be True. Therefore, it returns a bool Series, where each value represents a row of dataframe. If value is True, then it indicates that there is one or more NaN values in that row.
* **Step 3**: Then pass this bool Series to `[]` operator of dataframe i.e. `df[df.isnull().any(axis=1)]`. It returns only those rows where bool Series has True value. It means it returns only those rows which contain any NaN value.

In [181]:
df['col_1'] = [3,np.nan,3,3]

In [182]:
# df = pd.merge(df, pd.Series([np.nan,2,3,4], name="List"),left_index=True, right_index=True)
df

color  List_x  List_y  col_1  List
0    red       1     NaN    3.0   NaN
1  green       2     2.0    NaN   2.0
2   blue       3     3.0    3.0   3.0
3    red       4     4.0    3.0   4.0

In [183]:
df[df.isna().any(axis=1)]

color  List_x  List_y  col_1  List
0    red       1     NaN    3.0   NaN
1  green       2     2.0    NaN   2.0

#### `Find Most Frequent Value in a List`

In [192]:
mylist = [2,2,5,7,4,8,4,9,6,8,7,5,7]
mylist.count(4), mylist.count(9)

(2, 1)

In [ ]:
freq = max(set(mylist), key = mylist.count)
freq

1. set(mylist) creates a set from the list mylist, removing any duplicate elements. In this case, the resulting set is {2, 4, 5, 6, 7, 8, 9}.

1. mylist.count(x) returns the number of occurrences of element x in the list mylist.

1. max(set(mylist), key=mylist.count) returns the element in the set set(mylist) that has the highest count in the list mylist. The key parameter specifies the function to be called on each element of the set to determine its sort order. In this case, key=mylist.count calls the count() function on each element of the set, so that the set is sorted based on the count of each element in mylist.

## Change float display options
#### numpy

In [3]:
import numpy as np
np.set_printoptions(suppress=True)
print(345e12)

345000000000000.0


#### pandas

In [8]:
import pandas as pd
pd.set_option('display.float_format', lambda x: '%0.4f' %x)


In [2]:
import numpy as np
from scipy.sparse import csr_matrix

# create a 2-D representation of the matrix
A = np.array([[1, 0, 0, 0, 0, 0], [0, 0, 2, 0, 0, 1],\
 [0, 0, 0, 2, 0, 0]])
print("Dense matrix representation: \n", A)

# convert to sparse matrix representation 
S = csr_matrix(A)
print("Sparse matrix: \n",S)

# convert back to 2-D representation of the matrix
B = S.todense()
print("Dense matrix: \n", B)

S.toarray()

Dense matrix representation: 
 [[1 0 0 0 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
Sparse matrix: 
   (0, 0)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2
Dense matrix: 
 [[1 0 0 0 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


array([[1, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 1],
       [0, 0, 0, 2, 0, 0]])

In [ ]:
# Quick utility to embed the videos below
from IPython.display import YouTubeVideo
def embed_video(index, playlist='PLYCpMb24GpOC704uO9svUrihl-HY1tTJJ'):
    return YouTubeVideo('', index=index - 1, list=playlist, width=600, height=350)

embed_video(1)

In [1]:
matrix = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
]

list(zip(*matrix))

[(1, 5, 9), (2, 6, 10), (3, 7, 11), (4, 8, 12)]

In [2]:
[*matrix]

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]